server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_guard_storage?useSSL=false&serverTimezone=UTC
    username: root
    password: ashiq
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: wakeuppallob@gmail.com
    password: vxmy ryqs aowb qfnk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwt:
    secret: "zE@83w$GkPl1mvXqr9!Bd7TJ2g#sH5Lc"
    access-token-expiration: "PT15M"
    refresh-token-expiration: "PT168H"  # 7 days = 168 hours
    verification-token-expiration: "PT30M"