package com.ashiq.AuthGuard.entity;

public enum Role {
    ROLE_SUPER_ADMIN,
    ROLE_ADMIN,
    ROLE_VENDOR,
    ROLE_CUSTOMER,
    ROLE_DELIVERY,
    ROLE_SUPPORT,
    ROLE_FINANCE,
    ROLE_MARKETING,
    ROLE_WAREHOUSE,
    ROLE_QUALITY,
    ROLE_REGION_MANAGER
}
